#include "parse_map.h"

void init_parse_map(struct reader_table *table) {
  reader *pointers = &table->pointers[0];
  pointers['\0'] = &p_exit; // 0
  pointers[0x1] = NULL;
  pointers[0x2] = NULL;
  pointers[0x3] = NULL;
  pointers[0x4] = NULL;
  pointers[0x5] = NULL;
  pointers[0x6] = NULL;
  pointers[0x7] = NULL;
  pointers[0x8] = NULL;
  pointers[0x9] = NULL;
  pointers['\n'] = &p_exit; // A
  pointers[0xB] = NULL;
  pointers[0xC] = NULL;
  pointers[0xD] = NULL;
  pointers[0xE] = NULL;
  pointers[0xF] = NULL;
  pointers[0x10] = NULL;
  pointers[0x11] = NULL;
  pointers[0x12] = NULL;
  pointers['\r'] = &p_exit; // 13
  pointers[0x14] = NULL;
  pointers[0x15] = NULL;
  pointers[0x16] = NULL;
  pointers[0x17] = NULL;
  pointers[0x18] = NULL;
  pointers[0x19] = NULL;
  pointers[0x1A] = NULL;
  pointers[0x1B] = NULL;
  pointers[0x1C] = NULL;
  pointers[0x1D] = NULL;
  pointers[0x1E] = NULL;
  pointers[0x1F] = NULL;
  pointers[' '] = &p_skip;        // 20
  pointers['!'] = NULL;           // 21
  pointers['\"'] = NULL;          // 22
  pointers['#'] = NULL;           // 23
  pointers['$'] = NULL;           // 24
  pointers['%'] = NULL;           // 25
  pointers['&'] = NULL;           // 26
  pointers['\''] = NULL;          // 27
  pointers['('] = &p_open_paren;  // 28
  pointers[')'] = &p_close_paren; // 29
  pointers['*'] = &p_binary;      // 2A
  pointers['+'] = &p_binary;      // 2B
  pointers[','] = NULL;           // 2C
  pointers['-'] = &p_minus;       // 2D
  pointers['.'] = &p_const;       // 2E
  pointers['/'] = &p_binary;      // 2F
  pointers['0'] = &p_const;       // 30
  pointers['1'] = &p_const;       // 31
  pointers['2'] = &p_const;       // 32
  pointers['3'] = &p_const;       // 33
  pointers['4'] = &p_const;       // 34
  pointers['5'] = &p_const;       // 35
  pointers['6'] = &p_const;       // 36
  pointers['7'] = &p_const;       // 37
  pointers['8'] = &p_const;       // 38
  pointers['9'] = &p_const;       // 39
  pointers[':'] = NULL;           // 3A
  pointers[';'] = &p_exit;        // 3B
  pointers['<'] = NULL;           // 3C
  pointers['='] = NULL;           // 3D
  pointers['>'] = NULL;           // 3E
  pointers['?'] = NULL;           // 3F
  pointers['@'] = NULL;           // 40
  pointers['A'] = NULL;           // 41
  pointers['B'] = NULL;           // 42
  pointers['C'] = NULL;           // 43
  pointers['D'] = NULL;           // 44
  pointers['E'] = NULL;           // 45
  pointers['F'] = NULL;           // 46
  pointers['G'] = NULL;           // 47
  pointers['H'] = NULL;           // 48
  pointers['I'] = NULL;           // 49
  pointers['J'] = NULL;           // 4A
  pointers['K'] = NULL;           // 4B
  pointers['L'] = NULL;           // 4C
  pointers['M'] = NULL;           // 4D
  pointers['N'] = NULL;           // 4E
  pointers['O'] = NULL;           // 4F
  pointers['P'] = NULL;           // 50
  pointers['Q'] = NULL;           // 51
  pointers['R'] = NULL;           // 52
  pointers['S'] = NULL;           // 53
  pointers['T'] = NULL;           // 54
  pointers['U'] = NULL;           // 55
  pointers['V'] = NULL;           // 56
  pointers['W'] = NULL;           // 57
  pointers['X'] = NULL;           // 58
  pointers['Y'] = NULL;           // 59
  pointers['Z'] = NULL;           // 5A
  pointers['['] = NULL;           // 5B
  pointers['\\'] = &p_function;   // 5C
  pointers[']'] = NULL;           // 5D
  pointers['^'] = &p_binary;      // 5E
  pointers['_'] = &p_binary;      // 5F
  pointers['`'] = NULL;           // 60
  pointers['a'] = &p_variable;    // 61
  pointers['b'] = &p_variable;    // 62
  pointers['c'] = &p_variable;    // 63
  pointers['d'] = &p_variable;    // 64
  pointers['e'] = &p_eulers;      // 65
  pointers['f'] = &p_variable;    // 66
  pointers['g'] = &p_variable;    // 67
  pointers['h'] = &p_variable;    // 68
  pointers['i'] = &p_variable;    // 69
  pointers['j'] = &p_variable;    // 6A
  pointers['k'] = &p_variable;    // 6B
  pointers['l'] = &p_variable;    // 6C
  pointers['m'] = &p_variable;    // 6D
  pointers['n'] = &p_variable;    // 6E
  pointers['o'] = &p_variable;    // 6F
  pointers['p'] = &p_variable;    // 70
  pointers['q'] = &p_variable;    // 71
  pointers['r'] = &p_variable;    // 72
  pointers['s'] = &p_variable;    // 73
  pointers['t'] = &p_variable;    // 74
  pointers['u'] = &p_variable;    // 75
  pointers['v'] = &p_variable;    // 76
  pointers['w'] = &p_variable;    // 77
  pointers['x'] = &p_variable;    // 78
  pointers['y'] = &p_variable;    // 79
  pointers['z'] = &p_variable;    // 7A
  pointers['{'] = NULL;           // 7B
  pointers['|'] = NULL;           // 7C
  pointers['}'] = NULL;           // 7D
  pointers['~'] = NULL;           // 7E
  pointers[0x7F] = NULL;
  INITIALIZED_READER_TABLE = 1;
}

